### ISSUE TITLE
Add link from session times to world clock site?

### ISSUE THREAD

**Issue by jbrains** [pubmob-com/pubmob#7]
For example, timeanddate.com lets us do this:

https://www.timeanddate.com/worldclock/fixedtime.html?iso=20200827T1230&ah=1&am=15

Parameters:

- `iso`: starting instant in ISO format
- `ah`: length of event, hours portion
- `am`: length of event, minutes portion

Sadly, `am=75` doesn't work for "75 minutes". I tried.

**Comment by jlangr** [comment]
I'm working on something currently. The stupid API they provide gives times in *my* time since it's my account... and now it turns out that it's my time adjusted for DST, which makes it a little harder to convert to UTC. So that's problem 1.

Problem 2 is making the output useful--I'm about done with that; it's a bit of JS to find all the dates and convert them to local time using moment.js.

I thought about a link a while ago, so thanks for the reminder. I will add that in addition to showing the times in your local time--it would still be a useful tool.

BTW if you get a minute please send me the dates & times of the things you've currently scheduled (and for what TZ); I will use that to cross-check what I'm calculating.

Time is a pain.

**Comment by jbrains** [comment]
I'm about to send a pull request with my schedule.

I'll take a stab at putting links and then at least we have a backup plan.

**Comment by jbrains** [comment]
I sent pull request #8 with my schedule.

**Comment by jbrains** [comment]
You have a backup plan / ripcord in #9

**Comment by jlangr** [comment]
implemented a while back
